name: Visualizing Codebase

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.3.0
        with:
          # A path (relative to the root of your repo) to where you would like the diagram to live. For example: images/diagram.svg. Default: diagram.svg
          output_file: images/codebase.svg
          max_depth: 10
